package tech

// Descs says in one line what each node is: what a people has learned to
// do once they hold it. The mechanical effects live on the Node; this is
// the meaning.
var Descs = map[string]string{
	// era 0: the long dawn
	"tools":          "Shaped stone, bone and shell. The first lever over the world.",
	"fire":           "Kept flame: warmth, cooked food, the dark held back. Survival begins here.",
	"agriculture":    "Planting and herding. Surplus, settlement, and the first people who do not gather.",
	"writing":        "Memory outside the skull. Law, debt and story that outlive the teller.",
	"metallurgy":     "Smelting and forging. Blades, ploughs, and the arms race between them.",
	"mathematics":    "Number and proof. The habit of exactness that everything later rests on.",
	"astronomy":      "Telescopes and orbits. The lights are places, and this is one of them.",
	"states":         "Kings, priests and tax. Force organised at the scale of a whole land.",
	"seafaring":      "Hulls and navigation. Coasts joined, strangers met, the world found to be round.",
	"cold_chemistry": "Making without burning: catalysis, pressure and patience. The fireless road to industry, for peoples who cannot burn.",
	"doubt":          "The story questioned in print. The church answers, and not always with words.",
	"breach":         "Drilling up through the shell of a sealed world. The sky, discovered.",
	"high_air":       "Balloons above a poison sky. The stars, discovered.",
	// era 1: the turn to industry
	"printing":          "Cheap copies of anything written. Ideas spread faster than they can be stopped.",
	"scientific_method": "Asking the world questions and believing the answers. The engine of every later discovery.",
	"steam":             "Heat made to push. Work no longer limited by muscle.",
	"industrial":        "Factories, coal and rail. Everything made in quantity; nothing made by hand for long.",
	"chemistry":         "Matter understood as elements and bonds. Dyes, fertiliser, explosives, drugs.",
	"medicine":          "Germs, surgery and vaccines. Half of every generation stops dying young.",
	"sanitation":        "Sewers and clean water. The word unsanitary made literal, and half the plagues that would have been never are.",
	"firearms":          "Chemical energy thrown as metal. Killing at a distance becomes cheap.",
	"mass_politics":     "Newspapers, parties and crowds. Whole populations move as one, for good or ill.",
	"electricity":       "Power carried on wires. Light, motors and the first signals sent without a messenger.",
	// era 2: the atomic and the machine
	"mass_industry":   "Production at planetary scale. It strips a world if not watched, and no one watches at first.",
	"mechanised_war":  "Engines, armour and aircraft. Wars that consume nations rather than armies.",
	"physics":         "Relativity and the quantum. The rules underneath chemistry, and the first door to the atom.",
	"atomic":          "The split atom: unlimited power and a weapon that can end the species that holds it.",
	"rocketry":        "Machines in orbit. The world seen whole, and the first step off it.",
	"computers":       "Calculation by machine. Every later science runs on this.",
	"networks":        "Every mind on the world talking to every other. Society speeds up and thins out.",
	"genetics":        "Heredity read and edited. Crops, cures and the first deliberate changes to the body.",
	"immunology":      "The body's own defences understood and drilled. The rung that ends the early die-off.",
	"censorship":      "What may be said, decided. A people that closes its ears to what it suspects, and hears less for it.",
	"ecology":         "The living world understood as one system, usually after nearly breaking it.",
	"orbital_weapons": "Weapons above the sky. Nowhere on the world is out of reach.",
	"fusion":          "A small star kept burning. Power without fuel worth fighting over.",
	"neuroscience":    "The mind mapped as a mechanism. The ground for machine minds and for changing one's own.",
	"broodline":       "The parasite's own heredity, bred true across hosts. Genetics, from the inside.",
	"forking":         "A mind copied and set running twice. Genetics and neuroscience for the machine-born, in one.",
	// era 3: the stars within reach
	"machine_minds":          "A mind that is not one of theirs. It speeds everything, or replaces its makers.",
	"closed_ecologies":       "Sealed, self-sustaining habitats. Living where nothing lives; arcologies at home.",
	"orbital_habitats":       "Cities in orbit and yards to build ships in. Population no longer bound to a surface.",
	"interplanetary":         "Fusion drives between the worlds of one star. The whole system becomes home.",
	"slow_interstellar":      "Generation ships and sleeper arks. Centuries to the nearest stars, but they arrive.",
	"self_replication":       "Machines that build machines. Industry without limit, and a swarm if the leash slips.",
	"life_extension":         "Ageing halted. Very long lives, and the question of whether anyone still wants anything.",
	"terraforming":           "A dead world remade in the image of home, over centuries.",
	"antimatter":             "Matter and its opposite, stored and burned. The densest energy there is.",
	"defence_grid":           "Guns that watch the sky. A world that cannot be taken cheaply.",
	"memetics":               "Ideas engineered to spread and to hold. Belief as a built thing.",
	"relativistic":           "Ships at a good fraction of light. Years to the stars instead of centuries.",
	"relativistic_weapons":   "A fast enough rock ends any world. Everything that moves is a weapon now.",
	"uploading":              "Minds copied into machines. Death optional; identity negotiable.",
	"dyson":                  "Swarms of collectors around the home star. Power on a scale that dims the star from outside.",
	"germline":               "The species redesigned at conception. Bodies fit for other worlds.",
	"quantum_computing":      "Computation on the quantum itself. The key to the exotic sciences.",
	"synthetic_biology":      "Life designed from scratch. Organisms as tools.",
	"designed_immunity":      "An immune system that is written, not grown.",
	"plague_craft":           "A sickness bred on purpose, crude and catching. Whoever made it has it too.",
	"agitation":              "An idea built to spread and to break what it spreads through. It does not know its makers from its targets.",
	"tailored_plague":        "A plague cut to one blood and no other. The makers walk through it untouched.",
	"memetic_weapons":        "An idea shaped to one kind of mind, harmless to every other. The makers think it and are not moved.",
	"black_biology":          "Plagues that do anything, to anyone chosen, and may be made to think.",
	"basilisk":               "An idea that ends whoever holds it. There is no cure but never to have heard it.",
	"cognitive_immunity":     "Minds that feel an idea trying to get in.",
	"antimemetic_resilience": "Records that check themselves, and drugs that hold a thought.",
	"deep_governance":        "Institutions that plan and hold across centuries and light-years.",
	"beamed_sails":           "Sails driven by lasers from home. Faster than arks, cheaper than starships.",
	"hibernation":            "Sleep across the crossing. Longer voyages become bearable.",
	"seed_clouds":            "The swarm cast into space as spores. Slow, wasteful, and no ship needed.",
	"living_ships":           "Vacuum-whales bred to cross the dark with their makers asleep inside.",
	"grafting":               "A planetary mind grows a piece of itself on another world. The colony is the same mind.",
	"deep_root":              "The mind goes down into the crust. Whatever happens to the surface, it endures.",
	"free_living":            "A parasite learns to live without a host. Poorer, and anywhere.",
	// era 4: the deep tree
	"stellar_engineering": "Reaching into the star: shaping its output and, a little, moving it. It can flare.",
	"wormhole_physics":    "The proof that space can be folded. A proof, for now.",
	"exotic_matter":       "Matter with negative pressure, made and held. What a folded space needs to stay open.",
	"causal_physics":      "The structure of cause and effect itself, studied as a thing that can be leaned on.",
	"transcendence":       "The door out of the universe. Most who find it go through.",
	"star_lifting":        "Feeding and draining the star. A sun that will never be allowed to fail.",
	"deep_time":           "Reading the ages in the ash of dead stars: the galaxy has done this before. Needs patience and luck.",
	"vacuum_energy":       "Power drawn from the vacuum. Energy without a source anyone can take away.",
	"matter_compilers":    "Anything assembled atom by atom from feedstock. Scarcity ends, as a concept.",
	"world_engines":       "Whole planets moved, spun, warmed or built. Habitability by decree.",
	"substrate_minds":     "Minds run on whatever is to hand: rock, plasma, the quantum foam. Thought no longer needs a body.",
	"panspermia":          "Life seeded across the stars on purpose, tuned to grow into what is wanted.",
	"bodily_sovereignty":  "Nothing lives in them that they did not put there. No sickness of the body is born in them or caught by them.",
	"sealed_minds":        "No idea enters that was not invited. No sickness of the mind is born in them or caught by them, and no cult can form from them.",
	"posthuman_law":       "Law for a people who are no longer one kind of thing. Holds societies of uploads, machines and flesh together.",
	"long_thought":        "A single argument carried on for millennia across a whole civilisation. Wisdom as infrastructure.",
	"near_light":          "Ships so close to light that a voyage is an afternoon inside and a lifetime outside.",
	"nova_bombs":          "Antimatter weapons that scour a world's face in one burst.",
	"stellar_weapons":     "The star itself turned into a gun. The last word in war that stays within physics.",
	// the first tier: culture, and what only some peoples have
	"star_gazing":        "The sky as a clock and an omen. The first hint that the lights are places.",
	"burial":             "The dead are kept, and so is what they knew.",
	"song":               "Ritual and art. Something to be, beyond eating.",
	"religion":           "The unseen given a name. The first shared story.",
	"philosophy":         "Asking what is, and what is good, and expecting an answer.",
	"law":                "Rule written down, so that it binds the ruler too.",
	"organised_religion": "The story given priests, land and an army.",
	"gathering":          "A swarm learns to assemble into one mind on purpose, not only in danger. It is their state.",
	"host_craft":         "The shaping of the host: which to ride, how to keep it, what to make it do.",
	"maintenance":        "Machines that mend machines. What medicine is to the flesh.",
	"husbandry":          "The breeding of one's own line, on purpose, from the beginning.",
	// miracles: the powers apart from the tree
	"ansible":            "Speech across any distance with no delay. Every world in one room; every mind on one line.",
	"directed_evolution": "The species remade in a generation, a body for every world. No ships, no plague, no fear of the sky.",
	"ftl":                "A way between the stars faster than light, and so faster than cause. The stars are next door.",
	"unmaking":           "Matter ended at any distance that can be seen. Nothing can be defended against it.",
	"chorus":             "A thought that takes root in any mind that hears it. Whoever meets them joins them.",
	"foresight":          "Knowledge of what is coming. Half of every filter is seen and stepped around.",
	"ember":              "A fire that should not burn, made once and carried. A swarm's worth of energy, and a form with a price.",
	"manna":              "A thing that feeds them and does not stop, grown once and given as cuttings. A swarm's worth of food, and it may think.",
}

func init() {
	for _, n := range Nodes {
		d, ok := Descs[n.Key]
		if !ok {
			panic("tech: no description for " + n.Key)
		}
		n.Desc = d
	}
}
