package history

import (
	"encoding/json"
	"go/format"
	"sort"

	"worldgen/data"
)

//go:generate go run ./gen

// The event vocabulary is data/events.json: one entry per kind, with the
// parameters an event of it declares, a one-line meaning, and for a fact
// its sort and weight. The simulation reads its mechanics from the file
// and never its text; the constants in kinds_gen.go are generated from it
// so a kind the code emits is always one the file declares.

// KindDef is one entry of the table.
type KindDef struct {
	Kind    Kind     `json:"kind"`
	Sort    string   `json:"sort,omitempty"`
	Weight  float64  `json:"weight,omitempty"`
	Params  []string `json:"params"`
	Meaning string   `json:"meaning"`
}

var kindDefs []KindDef
var shapes = map[Kind]shape{}

func init() {
	raw, err := data.FS.ReadFile("events.json")
	if err != nil {
		panic("history: events.json: " + err.Error())
	}
	var t struct {
		Kinds []KindDef `json:"kinds"`
	}
	if err := json.Unmarshal(raw, &t); err != nil {
		panic("history: events.json: " + err.Error())
	}
	kindDefs = t.Kinds
	for _, d := range kindDefs {
		sh := shape{Params: d.Params, Sort: Nothing, Weight: d.Weight, Meaning: d.Meaning}
		if d.Weight > 0 {
			found := false
			for i, n := range sortNames {
				if n == d.Sort {
					sh.Sort, found = Sort(i), true
				}
			}
			if !found {
				panic("history: events.json: kind " + string(d.Kind) + " has weight and no sort")
			}
		}
		if _, dup := shapes[d.Kind]; dup {
			panic("history: events.json: kind " + string(d.Kind) + " twice")
		}
		shapes[d.Kind] = sh
	}
}

// Kinds lists the vocabulary in table order.
func Kinds() []KindDef { return kindDefs }

// Params lists the keys an event's kind declares, in order.
func (e *Event) Params() []string { return shapes[e.Kind].Params }

// Keys lists the keys an event carries, in order.
func (e *Event) Keys() []string {
	out := make([]string, 0, len(e.P))
	for k := range e.P {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// KindsSource is kinds_gen.go as the table says it should read.
func KindsSource() string {
	s := "// Code generated by go generate from data/events.json; DO NOT EDIT.\n\npackage history\n\nconst (\n"
	for _, d := range kindDefs {
		s += "\t" + d.Const() + " Kind = \"" + string(d.Kind) + "\"\n"
	}
	out, err := format.Source([]byte(s + ")\n"))
	if err != nil {
		panic("history: kinds_gen.go: " + err.Error())
	}
	return string(out)
}

// Const is the Go name of a kind: FWar for the fact "war", KSystem for
// the line "system".
func (d KindDef) Const() string {
	name := "K"
	if d.Weight > 0 {
		name = "F"
	}
	up := true
	for _, r := range d.Kind {
		switch {
		case r == '_':
			up = true
		case up:
			name += string(r - 'a' + 'A')
			up = false
		default:
			name += string(r)
		}
	}
	return name
}

// String is the record on one line, for digests and diffs: the year, the
// kind, the fields and the parameters by key.
func (e *Event) String() string {
	s := sprintf("%d\t%s\t%d\t%d\t%d\t%d\t%d\t%d", e.Year, e.Kind, e.Subject, e.Object, e.Star, e.Legacy, e.Plague, e.N)
	for _, k := range e.Keys() {
		s += sprintf("\t%s=%v", k, e.P[k])
	}
	return s
}
